<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <RootNamespace>MacroForge.App</RootNamespace>
    <AssemblyName>MacroForge</AssemblyName>
    <Product>Universal Mouse Macro Manager</Product>
    <Company>reiKama414</Company>
    <Authors>reiKama414</Authors>
    <Copyright>Copyright (c) 2026 reiKama414</Copyright>
    <Description>Universal mouse macro manager by reiKama414</Description>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MacroForge.Core\MacroForge.Core.csproj" />
  </ItemGroup>

</Project>
